version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  kbac-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./resources:/app/resources:ro
      - ./data:/app/data
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
    depends_on:
      qdrant:
        condition: service_healthy
    command: ["python", "-m", "kbac.api_server"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  kbac-web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./resources:/app/resources:ro
      - ./data:/app/data
      - ./.streamlit:/app/.streamlit
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
    depends_on:
      kbac-api:
        condition: service_healthy
    command: ["streamlit", "run", "kbac/web_app.py", "--server.port=8501", "--server.address=0.0.0.0"]

  kbac-cli:
    build: .
    volumes:
      - ./resources:/app/resources:ro
      - ./data:/app/data
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      qdrant:
        condition: service_healthy
    command: ["python", "-m", "kbac.cli"]

volumes:
  qdrant_storage:
